version: '3.8'

services:
  bot:
    build: .
    env_file:
      - './.env'
    volumes:
      - .:/usr/src/app
    command: python3 bot.py
  db:
    image: redis:7.2-rc-alpine
    ports: 
      - "6379:6379"
    restart: always
    volumes:
      - redis_db:/data

volumes:
  redis_db: