version: '3.8'

services:
  bot_service:
    build: .
    env_file:
      - './.env'
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: python3 bot.py
  db:
    image: redis:7.2-rc-alpine
    expose: 
      - "6379"
    restart: always
    volumes:
      - redis_db:/data

volumes:
  redis_db: